version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install redis
      - run: brew services start redis
      - run: brew install mysql
      - run: brew services start mysql
      - checkout
      - run: swift build
      - run: echo "CREATE DATABASE vapor_test" | mysql -uroot
      # - run: swift build -c release
      - run: swift test

  linux:
    docker:
      - image: swift:4.0
      - image: redis:3.2
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_test
          # MYSQL_ROOT_HOST: %
          MYSQL_USER: root
          # MYSQL_PASSWORD: vapor
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      # - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - macos
      - linux
